DATA_PATH_VGSALES = "data/vgsales.csv"
DATA_PATH_SALES = "data/sales.csv"

ASSET_PATH_ELBOWPLOT = "assets/elbow-test.jpg"
ASSET_PATH_SILHOUETTEPLOT = "assets/silhouette.jpg"
ASSET_PATH_RECOMMENDATIONS = "assets/recommendations.txt"
ASSET_PATH_CORRELATION = "assets/correlation"
ASSET_PATH_CLUSTERSPLOT = "assets/clusters.jpg"
ASSET_PATH_CLUSTERS_VALUATION = "assets/clusters-values.txt"
ASSET_PATH_GAMESMODEL = "assets/games-model.mdl"
ASSET_PATH_REGRESSIONS_DUMP = "assets/regressions-scores.txt"
ASSET_PATH_PREDICTIONS_DUMP = "assets/regressions-predictions.txt"
